gem install bundler
rails new .
#     cat Gemfile
#     source 'https://rubygems.org'
#     
#     gem 'bundler', '>=1.3.5'
#     
#     # Rails autogenerated
#     gem 'rails', '4.0.0'
#     gem 'sqlite3'
#     gem 'uglifier', '>= 1.3.0'
#     gem 'jquery-rails'
#     gem 'turbolinks'
#     
#     group :doc do
#       # bundle exec rake doc:rails generates the API under doc/api.
#       gem 'sdoc', require: false
#     end
#     
#     gem 'unicorn'
#     
#     # App-specific gems
#     ruby '1.9.3'
#     gem 'pg', :group => :production
bundle install

# Edit config/routes.rb, make a root mapping
vim config/routes.rb
rake db:create

# Necessary for heroku
git add .
git commit

heroku apps:create fit-workshop
heroku addons:add heroku-postgresql:dev
git push heroku master
